/* GHAZI ABBAS JEE 2028 TRACKER — modular browser-only app */
(() => {
  'use strict';
  const ADMIN_PASSWORD = 'JEE2028';
  const KEY = 'ghazi_jee_2028_v4';
  const defaultDB = {
    '11th': {
      Physics: ['Units and Dimensions','Mathematical Tools','Motion in a Straight Line','Motion in a Plane','Laws of Motion','Work, Energy and Power','Centre of Mass and System of Particles','Rotational Motion','Gravitation','Mechanical Properties of Solids','Mechanical Properties of Fluids','Thermal Properties of Matter','Thermodynamics','Kinetic Theory','Oscillations','Waves'],
      Chemistry: ['Some Basic Concepts of Chemistry','Structure of Atom','Classification of Elements and Periodicity','Chemical Bonding and Molecular Structure','Thermodynamics','Equilibrium','Redox Reactions','Organic Chemistry – Some Basic Principles','Hydrocarbons','States of Matter'],
      Maths: ['Sets','Relations and Functions','Trigonometric Functions','Complex Numbers and Quadratic Equations','Linear Inequalities','Permutations and Combinations','Binomial Theorem','Sequences and Series','Straight Lines','Conic Sections','Introduction to Three Dimensional Geometry','Limits and Derivatives','Statistics','Probability']
    },
    '12th': {
      Physics: ['Electric Charges and Fields','Electrostatic Potential and Capacitance','Current Electricity','Moving Charges and Magnetism','Magnetism and Matter','Electromagnetic Induction','Alternating Current','Electromagnetic Waves','Ray Optics and Optical Instruments','Wave Optics','Dual Nature of Radiation and Matter','Atoms','Nuclei','Semiconductor Electronics'],
      Chemistry: ['Solutions','Electrochemistry','Chemical Kinetics','Surface Chemistry','p-Block Elements','d and f Block Elements','Coordination Compounds','Haloalkanes and Haloarenes','Alcohols Phenols and Ethers','Aldehydes Ketones and Carboxylic Acids','Amines','Biomolecules','Polymers','Chemistry in Everyday Life'],
      Maths: ['Relations and Functions','Inverse Trigonometric Functions','Matrices','Determinants','Continuity and Differentiability','Application of Derivatives','Integrals','Application of Integrals','Differential Equations','Vector Algebra','Three Dimensional Geometry','Linear Programming','Probability']
    }
  };
  const state = load();
  const app = document.getElementById('app');
  const toastEl = document.getElementById('toast');
  let timer = {id:null,seconds:25*60,mode:'Focus',running:false};
  let pressTimer = null, longPress = false;

  function load(){
    try{
      const raw=localStorage.getItem(KEY); if(raw){const x=JSON.parse(raw); return normalize(x)}
    }catch(e){}
    const x={db:buildDB(),progress:{},xp:0,watchedSeconds:0,awardedMinutes:{},lastLecture:null,streak:{last:null,days:0},planner:{daily:60,weekly:600},settings:{revision:[1,7,21,45]}};
    saveObj(x); return x;
  }
  function buildDB(){
    const db={}; Object.entries(defaultDB).forEach(([cls,subs])=>{db[cls]={};Object.entries(subs).forEach(([sub,chaps])=>{db[cls][sub]={chapters:chaps.map((name,i)=>({id:slug(name),name,order:i+1,lectures:[]}))}})}); return db;
  }
  function normalize(x){
    x.db ||= buildDB(); x.progress ||= {}; x.xp ||= 0; x.watchedSeconds ||= 0; x.awardedMinutes ||= {}; x.settings ||= {revision:[1,7,21,45]}; x.streak ||= {last:null,days:0}; x.planner ||= {daily:60,weekly:600};
    return x;
  }
  function saveObj(x=state){localStorage.setItem(KEY,JSON.stringify(x))}
  function slug(s){return String(s).toLowerCase().trim().replace(/&/g,'and').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')}
  function esc(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
  function fmt(sec){sec=Math.max(0,Math.floor(sec||0));const h=Math.floor(sec/3600),m=Math.floor(sec%3600/60),s=sec%60;return h?`${h}:${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`:`${m}:${String(s).padStart(2,'0')}`}
  function pct(a,b){return b?Math.min(100,Math.round(a/b*100)):0}
  function toast(msg){toastEl.textContent=msg;toastEl.classList.add('show');clearTimeout(toastEl._t);toastEl._t=setTimeout(()=>toastEl.classList.remove('show'),2300)}
  function route(){let p=decodeURIComponent(location.pathname.replace(/\/+$/,'')); if(!p||p==='/')return ['home']; const q=new URLSearchParams(location.search); if(q.get('route'))p=q.get('route'); const a=p.split('/').filter(Boolean); if(a[0]==='dashboard')return ['dashboard']; if(a[0]==='search')return ['search']; if(a[0]==='planner')return ['planner']; if(a[0]==='analytics')return ['analytics']; if(a[0]==='admin')return ['admin']; if(a.length===1&&(a[0]==='11th'||a[0]==='12th'))return ['class',a[0]]; if(a.length===2&&(a[0]==='11th'||a[0]==='12th'))return ['subject',a[0],titleCase(a[1])]; if(a.length>=3&&(a[0]==='11th'||a[0]==='12th'))return ['chapter',a[0],titleCase(a[1]),a.slice(2).join('-')]; return ['home']}
  function titleCase(s){const map={physics:'Physics',chemistry:'Chemistry',maths:'Maths'};return map[String(s).toLowerCase()]||s}
  function navigate(path){history.pushState({},'',path);render()}
  window.navigate=navigate;
  window.addEventListener('popstate',render);
  document.addEventListener('keydown',e=>{if(e.target.matches('input,textarea,select'))return;if(e.key==='Escape')closeModal();});

  function header(){return `<header class="topbar"><a class="brand" href="/" onclick="event.preventDefault();navigate('/')"><img src="https://i.postimg.cc/m2PRngnY/logo512-png.png"><span class="brand-pill">GHAZI ABBAS ✔</span></a><nav class="nav"><button class="btn" onclick="navigate('/dashboard')">Dashboard</button><button class="btn" onclick="navigate('/11th')">11th</button><button class="btn" onclick="navigate('/12th')">12th</button><button class="btn" onclick="navigate('/search')">Search</button><button class="btn" onclick="navigate('/analytics')">Analytics</button><button class="btn blue" onclick="navigate('/planner')">Planner</button><button class="btn" onclick="navigate('/admin')">🔒 Admin</button></nav></header>`}
  function shell(content){return `<div class="shell">${header()}${content}<div class="footer">GHAZI ABBAS • JEE 2028 AIR 1 • Built for focused study</div></div>`}
  function allChapters(){const out=[];for(const [cls,subs] of Object.entries(state.db))for(const [sub,obj] of Object.entries(subs))obj.chapters.forEach(c=>out.push({...c,cls,sub}));return out}
  function allLectures(){return allChapters().flatMap(c=>c.lectures.map(l=>({...l,cls:c.cls,sub:c.sub,chapter:c.name,chapterId:c.id})))}
  function chapterBy(cls,sub,id){const obj=state.db?.[cls]?.[sub];return obj?.chapters.find(c=>c.id===id)||null}
  function chapterProgress(c){const ls=c.lectures||[];if(!ls.length)return 0;const total=ls.reduce((a,l)=>a+(Number(l.duration)||0),0);const watched=ls.reduce((a,l)=>a+Math.min(Number(l.duration)||0,Number(state.progress[l.id]?.seconds)||0),0);return pct(watched,total)}
  function subjectProgress(cls,sub){const cs=state.db[cls][sub].chapters;return cs.length?Math.round(cs.reduce((a,c)=>a+chapterProgress(c),0)/cs.length):0}
  function totalStats(){const ls=allLectures();const total=ls.reduce((a,l)=>a+(Number(l.duration)||0),0);const watched=ls.reduce((a,l)=>a+Math.min(Number(l.duration)||0,Number(state.progress[l.id]?.seconds)||0),0);const done=ls.filter(l=>Number(state.progress[l.id]?.seconds)>=Math.max(1,(Number(l.duration)||0)*.9)).length;return {ls,total,watched,done,p:pct(watched,total)}}
  function home(){const st=totalStats();return shell(`<main><section class="hero"><span class="eyebrow"><i class="dot"></i> JEE 2028 PERSONAL COMMAND CENTER</span><h1>JEE 2028 — AIR 1</h1><h2>IIT BOMBAY • COMPUTER SCIENCE</h2><p>A clean, fast and distraction-free study system for Class 11th + 12th PCM — chapters, lectures, notes, DPP, PYQ, revision, tests and progress in one place.</p><div class="hero-actions"><button class="btn pink" onclick="continueLearning()">▶ Continue Learning</button><button class="btn" onclick="navigate('/11th')">Explore 11th</button><button class="btn" onclick="navigate('/12th')">Explore 12th</button></div></section><section class="dashboard-grid">${stat('⚡','XP',state.xp,'1 XP per actual minute watched','xp-text')}${stat('▶','LECTURE TIME',fmt(st.watched),`${st.done}/${st.ls.length} completed`)}${stat('📈','OVERALL PROGRESS',st.p+'%','Across uploaded lectures')}${stat('🔥','STREAK',state.streak.days+' days','Study activity')}</section><section class="section"><div class="section-head"><div><h2>Choose your battlefield</h2><p>PCM is separated cleanly by class and subject. Open a subject, then any chapter.</p></div></div><div class="subject-grid">${subjectCard('11th','Physics','⚡','physics')}${subjectCard('11th','Chemistry','🧪','chemistry')}${subjectCard('11th','Maths','📐','maths')}${subjectCard('12th','Physics','⚡','physics')}${subjectCard('12th','Chemistry','🧪','chemistry')}${subjectCard('12th','Maths','📐','maths')}</div></section><section class="section"><div class="section-head"><div><h2>Quick actions</h2><p>No hunting around the site.</p></div></div><div class="toolbar"><button class="btn" onclick="navigate('/planner')">⏱ Study Timer</button><button class="btn" onclick="navigate('/search')">⌕ Find a chapter / lecture</button><button class="btn" onclick="navigate('/analytics')">▥ View Analytics</button><button class="btn" onclick="navigate('/admin')">⚙ Manage Content</button></div></section></main>`)}
  function stat(icon,label,value,sub,cls=''){return `<div class="stat"><span class="stat-label">${icon} ${label}</span><strong class="stat-value ${cls}">${value}</strong><span class="stat-sub">${sub}</span></div>`}
  function subjectCard(cls,sub,icon,kind){const p=subjectProgress(cls,sub);const count=state.db[cls][sub].chapters.length;return `<article class="subject-card ${kind}"><span class="subject-icon">${icon}</span><div class="subject-kicker">Class ${cls}</div><h3>${sub}</h3><p>${count} chapters • ${state.db[cls][sub].chapters.reduce((a,c)=>a+c.lectures.length,0)} lectures uploaded.</p><div class="progress-line"><i style="width:${p}%"></i></div><div class="progress-row"><span>Progress</span><b>${p}%</b></div><div class="chapter-actions"><button class="btn" onclick="navigate('/${cls}/${sub.toLowerCase()}')">Open ${sub}</button></div></article>`}

  function classPage(cls){return shell(`<main><div class="page-head"><div class="breadcrumbs"><a href="/" onclick="event.preventDefault();navigate('/')">Home</a><span>›</span><b>Class ${cls}</b></div><h1>Class ${cls} • PCM</h1><p>All Physics, Chemistry and Maths chapters are listed here. Click a chapter to enter its lecture/resource workspace.</p></div><div class="subject-grid">${['Physics','Chemistry','Maths'].map((s,i)=>subjectCard(cls,s,['⚡','🧪','📐'][i],['physics','chemistry','maths'][i])).join('')}</div><section class="section"><div class="section-head"><div><h2>All chapters</h2><p>Sorted in study order.</p></div></div><div class="chapter-grid">${['Physics','Chemistry','Maths'].flatMap(s=>state.db[cls][s].chapters.map((c,i)=>chapterCard(cls,s,c))).join('')}</div></section></main>`)}
  function subjectPage(cls,sub){const obj=state.db?.[cls]?.[sub];if(!obj)return home();return shell(`<main><div class="page-head"><div class="breadcrumbs"><a href="/${cls}" onclick="event.preventDefault();navigate('/${cls}')">Class ${cls}</a><span>›</span><b>${sub}</b></div><h1>${sub} • Class ${cls}</h1><p>${obj.chapters.length} chapters. Open any chapter for lectures, notes, DPP, module, PYQ, revisions and tests.</p></div><div class="toolbar"><input id="chapterSearch" class="search" placeholder="Search ${sub} chapters..." oninput="filterChapters()"><button class="btn active">All chapters</button></div><div id="chapterGrid" class="chapter-grid">${obj.chapters.map(c=>chapterCard(cls,sub,c)).join('')}</div></main>`)}
  function chapterCard(cls,sub,c){const l=c.lectures.length,p=chapterProgress(c);return `<article class="chapter-card" data-name="${esc(c.name.toLowerCase())}"><span class="chapter-no">CHAPTER ${String(c.order).padStart(2,'0')}</span><h3>${esc(c.name)}</h3><div class="mini-meta"><span class="tag blue">${l} lecture${l!==1?'s':''}</span><span class="tag">${p}% watched</span></div><div class="progress-line"><i style="width:${p}%"></i></div><div class="chapter-actions"><button class="btn" onclick="navigate('/${cls}/${sub.toLowerCase()}/${c.id}')">Open Chapter</button></div></article>`}
  function filterChapters(){const q=(document.getElementById('chapterSearch')?.value||'').toLowerCase();document.querySelectorAll('#chapterGrid .chapter-card').forEach(x=>x.style.display=x.dataset.name.includes(q)?'':'none')}
  window.filterChapters=filterChapters;

  function chapterPage(cls,sub,id){const c=chapterBy(cls,sub,id);if(!c)return home();const ls=[...c.lectures].sort((a,b)=>a.no-b.no);const next=ls.find(l=>(state.progress[l.id]?.seconds||0)<(Number(l.duration||0)*.9));const p=chapterProgress(c);return shell(`<main><div class="page-head"><div class="breadcrumbs"><a href="/${cls}" onclick="event.preventDefault();navigate('/${cls}')">Class ${cls}</a><span>›</span><a href="/${cls}/${sub.toLowerCase()}" onclick="event.preventDefault();navigate('/${cls}/${sub.toLowerCase()}')">${sub}</a><span>›</span><b>${esc(c.name)}</b></div><h1>${esc(c.name)}</h1><p>${sub} • Class ${cls} • ${ls.length} lecture${ls.length!==1?'s':''}. Your progress, resources and revision schedule live here.</p></div><div class="content-layout"><div><div class="panel"><div class="overview-row"><div class="progress-ring" style="--pct:${p}%"><span>${p}%</span></div><div class="overview-copy"><h3>Chapter progress</h3><p>${ls.filter(l=>(state.progress[l.id]?.seconds||0)>=Number(l.duration||0)*.9).length} of ${ls.length} lectures completed. ${next?`Continue with Lecture ${next.no}.`:'Add lectures from Admin to start.'}</p></div></div></div><section class="section"><div class="section-head"><div><h2>Lectures</h2><p>Thumbnail, teacher, duration and live watch progress.</p></div>${next?`<button class="btn pink" onclick="openLecture('${cls}','${sub}','${c.id}','${next.id}')">▶ Continue</button>`:''}</div>${ls.length?`<div class="lecture-grid">${ls.map(l=>lectureCard(cls,sub,c,l)).join('')}</div>`:`<div class="empty">No lectures uploaded yet.<br><button class="btn" style="margin-top:12px" onclick="navigate('/admin')">Open Admin → Add Lecture</button></div>`}</section><section class="section"><div class="section-head"><div><h2>Study resources</h2><p>Resources attached to this chapter can be opened without leaving the site.</p></div></div>${resourceGrid(c,ls[0])}</section><section class="section"><div class="section-head"><div><h2>Smart revision</h2><p>Default schedule: R1 1d • R2 7d • R3 21d • R4 45d. Change it in Admin.</p></div></div><div class="revision-grid">${revisionCards(c)}</div></section></div><aside class="panel sticky"><div class="side-label">Chapter navigator</div><div class="side-list">${['Notes','DPP','Module','PYQ','Revision','Test'].map(x=>`<button class="side-link" onclick="document.getElementById('${x.toLowerCase()}Section')?.scrollIntoView({behavior:'smooth'})">${x}</button>`).join('')}</div><div class="side-label" style="margin-top:16px">Keyboard</div><div class="notice"><b>Space</b> play/pause • hold Space = 2×<br><b>← →</b> ±10 sec • <b>↑ ↓</b> volume<br><b>F</b> fullscreen</div></aside></div></main>`)}
  function lectureCard(cls,sub,c,l){const pr=state.progress[l.id]||{};const d=Number(l.duration)||0;const p=pct(pr.seconds||0,d);return `<article class="lecture-card"><div class="thumb">${l.thumbnail?`<img src="${esc(l.thumbnail)}" alt="">`:`<div class="thumb-fallback"><span style="font:800 28px Poppins;color:#fff">L${l.no}</span></div>`}<button class="play" onclick="openLecture('${cls}','${sub}','${c.id}','${l.id}')">▶</button>${p>=90?'<span class="watched-badge">✓ COMPLETED</span>':''}<span class="duration">${d?fmt(d):'AUTO'}</span></div><div class="lecture-body"><div class="lecture-number">LECTURE ${l.no}</div><div class="lecture-title">${esc(l.title||'Untitled Lecture')}</div><div class="lecture-meta">${esc(l.teacher||'Teacher not set')} • ${d?fmt(d):'duration auto-detect'}</div><div class="lecture-progress"><div class="progress-line"><i style="width:${p}%"></i></div><div class="progress-row"><span>${p}% watched</span><span>${fmt(pr.seconds||0)}</span></div></div><div class="lecture-actions"><button class="btn pink" onclick="openLecture('${cls}','${sub}','${c.id}','${l.id}')">${p?'Resume':'Start'}</button></div></div></article>`}
  function resourceGrid(c,l){const vals=[['Notes',l?.notesUrl],['DPP',l?.dppUrl],['Module',l?.moduleUrl],['PYQ',l?.pyqUrl],['Solutions',l?.solutionsUrl]];return `<div class="resource-grid">${vals.map(([n,u])=>`<button class="resource" onclick="openResource('${esc(n)}',${u?`'${esc(u)}'`:'null'})"><strong>${n}</strong><small>${u?'Open inside':'Not added'}</small></button>`).join('')}</div>`}
  function revisionCards(c){const base=c.revision||{};return state.settings.revision.map((d,i)=>{const key='r'+(i+1);const done=!!base[key];return `<div class="revision"><b>R${i+1}</b><span>${d} day${d!==1?'s':''} after learning</span><button class="btn ${done?'green':''}" onclick="toggleRevision('${c.cls||''}','${c.id}','${key}')">${done?'✓ Done':'Mark done'}</button></div>`}).join('')}
  function toggleRevision(cls,id,key){for(const [cl,subs] of Object.entries(state.db))for(const obj of Object.values(subs)){const c=obj.chapters.find(x=>x.id===id);if(c){c.revision||={};c.revision[key]=!c.revision[key];saveObj();toast(c.revision[key]?'Revision marked done':'Revision reopened');render();return}}}
  window.toggleRevision=toggleRevision;

  function openLecture(cls,sub,cid,lid){const c=chapterBy(cls,sub,cid), l=c?.lectures.find(x=>x.id===lid);if(!l)return;state.lastLecture=lid;saveObj();openModal(`<div class="modal-box" style="max-width:1200px"><div class="modal-head"><div><h3>Lecture ${l.no} • ${esc(l.title)}</h3><div class="lecture-meta">${esc(l.teacher||'Teacher')} • Duration detects automatically from video</div></div><button class="btn icon-btn" onclick="closeModal()">✕</button></div><div class="player-shell"><div class="video-stage"><video id="lectureVideo" controls preload="metadata" playsinline ${l.thumbnail?`poster="${esc(l.thumbnail)}"`:''} src="${esc(l.videoUrl||'')}"></video><div class="player-overlay"></div></div><div class="controls"><input id="seekBar" class="range" type="range" min="0" max="100" value="0" step="0.1"><div class="control-bar"><button class="btn" id="back10">−10</button><button class="btn pink" id="playBtn">▶ Play</button><button class="btn" id="fwd10">+10</button><button class="btn" id="muteBtn">🔊</button><input id="volBar" class="range" style="max-width:110px" type="range" min="0" max="1" step="0.05" value="1"><select id="speed" class="select speed-select"><option>.5×</option><option>.75×</option><option selected>1×</option><option>1.25×</option><option>1.5×</option><option>1.75×</option><option>2×</option><option>2.5×</option><option>3×</option></select><span class="timecode" id="timeCode">0:00 / Auto</span><span class="control-spacer"></span><span class="kbd">Space hold = 2×</span><button class="btn" id="fullBtn">⛶</button><button class="btn green" id="completeBtn">✓ Complete</button></div></div><div class="player-note">Shortcuts: <b>Space</b> play/pause • hold Space for temporary 2× • <b>←/→</b> 10 sec • <b>↑/↓</b> volume • <b>F</b> fullscreen. Watch time is counted from real playback, not seeking.</div></div><div style="display:flex;justify-content:space-between;gap:8px;margin-top:12px;flex-wrap:wrap"><div class="notice">Progress is saved automatically. XP is awarded only for actual playback minutes.</div><button class="btn blue" onclick="openLectureResources('${cls}','${sub}','${cid}','${lid}')">Resources</button></div></div>`);setupPlayer(cls,sub,cid,l)}
  window.openLecture=openLecture;
  function setupPlayer(cls,sub,cid,l){const v=document.getElementById('lectureVideo');if(!v)return;const pr=state.progress[l.id]||{seconds:0,xpSeconds:0};let lastWall=performance.now(),lastVideo=pr.seconds||0,seekIgnore=false;const seek=document.getElementById('seekBar'),tc=document.getElementById('timeCode');
    v.addEventListener('loadedmetadata',()=>{l.duration=Math.round(v.duration);saveObj();update();});
    v.addEventListener('loadeddata',()=>{try{v.currentTime=Math.min(pr.seconds||0,Math.max(0,(v.duration||1)-1))}catch(e){} update()});
    function update(){const d=v.duration||l.duration||0;seek.value=d?((v.currentTime/d)*100):0;tc.textContent=`${fmt(v.currentTime)} / ${d?fmt(d):'Auto'}`}
    v.addEventListener('timeupdate',()=>{update();const now=performance.now(),delta=(now-lastWall)/1000,vd=Math.abs(v.currentTime-lastVideo);lastWall=now;if(v.paused||delta<0||delta>1.8||vd>delta+1.5){lastVideo=v.currentTime;return} if(delta>0&&delta<1.8){pr.seconds=Math.max(pr.seconds||0,v.currentTime);pr.xpSeconds=(pr.xpSeconds||0)+delta;const before=Math.floor((pr.xpSeconds-delta)/60),after=Math.floor(pr.xpSeconds/60);if(after>before){state.xp+=after-before;state.watchedSeconds+=(after-before)*60;markStreak();saveObj();} else {saveObj()}}lastVideo=v.currentTime;if(v.duration&&v.currentTime/v.duration>=.9){pr.seconds=v.duration;pr.completed=true;saveObj()}});
    v.addEventListener('play',()=>{document.getElementById('playBtn').textContent='❚❚ Pause';lastWall=performance.now();lastVideo=v.currentTime});v.addEventListener('pause',()=>{document.getElementById('playBtn').textContent='▶ Play';saveObj()});
    document.getElementById('playBtn').onclick=()=>v.paused?v.play():v.pause();document.getElementById('back10').onclick=()=>v.currentTime=Math.max(0,v.currentTime-10);document.getElementById('fwd10').onclick=()=>v.currentTime=Math.min(v.duration||Infinity,v.currentTime+10);document.getElementById('volBar').oninput=e=>v.volume=Number(e.target.value);document.getElementById('muteBtn').onclick=()=>{v.muted=!v.muted;document.getElementById('muteBtn').textContent=v.muted?'🔇':'🔊'};document.getElementById('speed').onchange=e=>v.playbackRate=parseFloat(e.target.value);document.getElementById('fullBtn').onclick=()=>{const el=document.querySelector('.video-stage');if(document.fullscreenElement)document.exitFullscreen();else el.requestFullscreen?.()};document.getElementById('completeBtn').onclick=()=>{pr.seconds=v.duration||pr.seconds;pr.completed=true;saveObj();toast('Lecture marked complete ✓');render();openLecture(cls,sub,cid,l.id)};seek.oninput=e=>{seekIgnore=true;if(v.duration)v.currentTime=v.duration*(Number(e.target.value)/100);setTimeout(()=>seekIgnore=false,300)};
    function keydown(e){if(e.target.matches('input,textarea,select'))return;if(e.key===' '){e.preventDefault();if(!pressTimer){longPress=false;pressTimer=setTimeout(()=>{longPress=true;v.playbackRate=2; if(v.paused)v.play();},320)}}else if(e.key==='ArrowRight'){e.preventDefault();v.currentTime=Math.min(v.duration||Infinity,v.currentTime+10)}else if(e.key==='ArrowLeft'){e.preventDefault();v.currentTime=Math.max(0,v.currentTime-10)}else if(e.key==='ArrowUp'){e.preventDefault();v.volume=Math.min(1,v.volume+.1);document.getElementById('volBar').value=v.volume}else if(e.key==='ArrowDown'){e.preventDefault();v.volume=Math.max(0,v.volume-.1);document.getElementById('volBar').value=v.volume}else if(e.key.toLowerCase()==='f'){e.preventDefault();document.getElementById('fullBtn').click()}}
    function keyup(e){if(e.key===' '){clearTimeout(pressTimer);pressTimer=null;if(longPress){v.playbackRate=parseFloat(document.getElementById('speed').value);if(v.paused===false&&v.currentTime===0)v.pause()}else{v.paused?v.play():v.pause()}}}
    document.addEventListener('keydown',keydown);document.addEventListener('keyup',keyup);v._cleanup=()=>{document.removeEventListener('keydown',keydown);document.removeEventListener('keyup',keyup)};
  }
  function markStreak(){const d=new Date().toISOString().slice(0,10);if(state.streak.last===d)return;const prev=new Date(Date.now()-86400000).toISOString().slice(0,10);state.streak.days=state.streak.last===prev?state.streak.days+1:1;state.streak.last=d}
  function openLectureResources(cls,sub,cid,lid){const c=chapterBy(cls,sub,cid),l=c.lectures.find(x=>x.id===lid);openResource('Lecture resources',null,resourceGrid(c,l))}
  window.openLectureResources=openLectureResources;
  function openResource(title,url,html=''){if(!url&&!html){toast('Resource not added yet');return}openModal(`<div class="modal-box"><div class="modal-head"><h3>${esc(title)}</h3><button class="btn icon-btn" onclick="closeModal()">✕</button></div>${html?html:`<iframe class="pdf-frame" src="${esc(url)}" title="${esc(title)}"></iframe><div style="margin-top:9px;display:flex;justify-content:flex-end"><a class="btn" target="_blank" rel="noopener" href="${esc(url)}">Open in new tab ↗</a></div>`}</div>`)}
  window.openResource=openResource;
  function continueLearning(){const ls=allLectures();const l=state.lastLecture&&ls.find(x=>x.id===state.lastLecture)||ls.find(x=>(state.progress[x.id]?.seconds||0)>0&&(state.progress[x.id]?.seconds||0)<(x.duration||1)*.9)||ls.find(x=>!state.progress[x.id]?.completed);if(!l){toast('No lecture available yet');navigate('/admin');return}openLecture(l.cls,l.sub,l.chapterId,l.id)}
  window.continueLearning=continueLearning;

  function searchPage(){return shell(`<main><div class="page-head"><h1>Search your syllabus</h1><p>Find chapters and uploaded lectures instantly.</p></div><div class="toolbar"><input id="globalSearch" class="search" placeholder="e.g. unit dimensions, electrochemistry, lecture 7..." oninput="globalSearch()"></div><div id="searchResults" class="chapter-grid"><div class="empty">Start typing to search.</div></div></main>`)}
  function globalSearch(){const q=(document.getElementById('globalSearch')?.value||'').toLowerCase().trim();const box=document.getElementById('searchResults');if(!q){box.innerHTML='<div class="empty">Start typing to search.</div>';return}const ch=allChapters().filter(c=>(c.name+' '+c.sub+' '+c.cls).toLowerCase().includes(q));const ls=allLectures().filter(l=>(l.title+' '+l.teacher+' lecture '+l.no+' '+l.chapter).toLowerCase().includes(q));box.innerHTML=[...ch.map(c=>`<article class="chapter-card"><span class="chapter-no">CHAPTER</span><h3>${esc(c.name)}</h3><p>${c.sub} • Class ${c.cls}</p><button class="btn" onclick="navigate('/${c.cls}/${c.sub.toLowerCase()}/${c.id}')">Open</button></article>`),...ls.map(l=>`<article class="chapter-card"><span class="chapter-no">LECTURE ${l.no}</span><h3>${esc(l.title)}</h3><p>${esc(l.chapter)} • ${esc(l.sub)} • ${esc(l.cls)}</p><button class="btn pink" onclick="openLecture('${l.cls}','${l.sub}','${l.chapterId}','${l.id}')">Watch</button></article>`)].join('')||'<div class="empty">Nothing found.</div>'}
  window.globalSearch=globalSearch;

  function analyticsPage(){const st=totalStats();return shell(`<main><div class="page-head"><h1>Analytics</h1><p>A simple command-center view of your study progress.</p></div><div class="dashboard-grid">${stat('⚡','XP',state.xp,'Actual playback minutes','xp-text')}${stat('⏱','WATCHED',fmt(st.watched),'Lecture watch time')}${stat('✓','COMPLETED',st.done,`of ${st.ls.length} lectures`)}${stat('🔥','STREAK',state.streak.days+' days','Current study streak')}</div><section class="section"><div class="section-head"><div><h2>Subject progress</h2></div></div><div class="chapter-grid">${Object.entries(state.db).flatMap(([cls,subs])=>Object.keys(subs).map(sub=>`<div class="chapter-card"><span class="chapter-no">CLASS ${cls}</span><h3>${sub}</h3><div class="progress-line"><i style="width:${subjectProgress(cls,sub)}%"></i></div><div class="progress-row"><span>${subjectProgress(cls,sub)}%</span><span>${subs[sub].chapters.length} chapters</span></div></div>`)).join('')}</div></section><section class="section"><div class="panel"><h3 style="margin-top:0;font:650 18px Poppins">Tracking breakdown</h3><p class="notice">Lecture progress is calculated from actual playback seconds saved per lecture. XP is awarded once per minute of actual playback time.</p><div class="mini-meta" style="margin-top:14px"><span class="tag">Notes: chapter resources</span><span class="tag">DPP: optional / NO DPP</span><span class="tag">PYQ: chapter resources</span><span class="tag">Revision: configurable</span><span class="tag">Tests: chapter quizzes</span></div></div></section></main>`)}

  function plannerPage(){return shell(`<main><div class="page-head"><h1>Study Planner</h1><p>Use the timer for focused sessions and set daily/weekly targets.</p></div><div class="planner-grid"><div class="panel timer"><div class="timer-mode" id="timerMode">Focus</div><div class="timer-value" id="timerValue">25:00</div><div class="timer-actions"><button class="btn pink" onclick="toggleTimer()" id="timerBtn">Start</button><button class="btn" onclick="resetTimer()">Reset</button></div><div class="toolbar" style="justify-content:center;margin-top:18px"><button class="btn" onclick="setTimer(25,'Focus')">25m</button><button class="btn" onclick="setTimer(50,'Focus')">50m</button><button class="btn" onclick="setTimer(10,'Break')">10m Break</button></div></div><div class="panel"><h3 style="font:650 18px Poppins;margin-top:0">Targets</h3><div class="target-row"><input id="dailyTarget" type="number" min="1" value="${state.planner.daily}"><span class="tag">daily minutes</span></div><div class="target-row"><input id="weeklyTarget" type="number" min="1" value="${state.planner.weekly}"><span class="tag">weekly minutes</span></div><button class="btn blue" onclick="saveTargets()">Save targets</button><div style="margin-top:18px" class="notice">Timer minutes are a planning tool. Lecture XP remains tied to actual lecture playback.</div></div></div></main>`)}
  window.setTimer=(m,mode)=>{timer={id:null,seconds:m*60,mode,running:false};updateTimerUI()};window.toggleTimer=()=>{if(timer.running){clearInterval(timer.id);timer.running=false}else{timer.running=true;timer.id=setInterval(()=>{timer.seconds--;if(timer.seconds<=0){clearInterval(timer.id);timer.running=false;toast('Focus session complete 🎯')}updateTimerUI()},1000)}updateTimerUI()};window.resetTimer=()=>{timer.running=false;clearInterval(timer.id);timer={id:null,seconds:25*60,mode:'Focus',running:false};updateTimerUI()};function updateTimerUI(){const el=document.getElementById('timerValue');if(el)el.textContent=fmt(timer.seconds);const m=document.getElementById('timerMode');if(m)m.textContent=timer.mode;const b=document.getElementById('timerBtn');if(b)b.textContent=timer.running?'Pause':'Start'}window.saveTargets=()=>{state.planner.daily=Number(document.getElementById('dailyTarget').value)||60;state.planner.weekly=Number(document.getElementById('weeklyTarget').value)||600;saveObj();toast('Targets saved')};

  function adminPage(){if(sessionStorage.getItem('ghazi_admin')!=='yes')return shell(`<main class="admin-lock"><div class="lock-icon">🔐</div><h2>Admin Access</h2><p>Content management is locked.</p><input id="adminPass" class="password" type="password" placeholder="Enter admin password" onkeydown="if(event.key==='Enter')unlockAdmin()"><button class="btn pink" onclick="unlockAdmin()">Unlock Admin</button><div id="adminErr" style="color:#ff7eaa;font-size:11px;min-height:18px;margin-top:8px"></div></main>`);return shell(`<main><div class="page-head"><div class="breadcrumbs"><b>Admin CMS</b></div><h1>Content Control Room</h1><p>Add chapters and lectures without touching the source code. Data is stored in this browser until a cloud backend is connected.</p></div><div class="admin-tabs"><button class="btn active" onclick="adminTab('lecture')">＋ Lecture</button><button class="btn" onclick="adminTab('chapter')">＋ Chapter</button><button class="btn" onclick="adminTab('manage')">Manage</button><button class="btn" onclick="adminTab('data')">Backup</button><button class="btn danger" onclick="lockAdmin()">Lock</button></div><div id="adminBody">${adminLectureForm()}</div></main>`)}
  window.unlockAdmin=()=>{if(document.getElementById('adminPass').value===ADMIN_PASSWORD){sessionStorage.setItem('ghazi_admin','yes');toast('Admin unlocked 🔓');render()}else document.getElementById('adminErr').textContent='Wrong password'};window.lockAdmin=()=>{sessionStorage.removeItem('ghazi_admin');toast('Admin locked 🔒');render()};
  function adminLectureForm(){const classes=['11th','12th'];return `<div class="admin-grid"><div class="panel"><h3 style="font:650 18px Poppins;margin-top:0">Add lecture</h3><form class="form" onsubmit="addLecture(event)"><div class="field"><label>Class</label><select id="fClass" onchange="refreshAdminSubjects()">${classes.map(x=>`<option>${x}</option>`).join('')}</select></div><div class="field"><label>Subject</label><select id="fSubject" onchange="refreshAdminChapters()"><option>Physics</option><option>Chemistry</option><option>Maths</option></select></div><div class="field full"><label>Chapter</label><select id="fChapter"></select></div><div class="field"><label>Lecture number</label><input id="fNo" type="number" min="1" placeholder="Auto suggestion"></div><div class="field"><label>Title</label><input id="fTitle" required placeholder="e.g. Fundamental units"></div><div class="field"><label>Teacher</label><input id="fTeacher" placeholder="Teacher name"></div><div class="field"><label>Video URL</label><input id="fVideo" required placeholder="Direct MP4/WebM URL"></div><div class="field"><label>Thumbnail URL</label><input id="fThumb" placeholder="https://..."></div><div class="field"><label>Notes PDF URL</label><input id="fNotes" placeholder="https://..."></div><div class="field"><label>DPP PDF URL</label><input id="fDpp" placeholder="Leave blank for NO DPP"></div><div class="field"><label>Module URL</label><input id="fModule" placeholder="https://..."></div><div class="field"><label>PYQ URL</label><input id="fPyq" placeholder="https://..."></div><div class="field"><label>Solutions URL</label><input id="fSolutions" placeholder="https://..."></div><div class="field full"><label>Quiz JSON (optional)</label><textarea id="fQuiz" placeholder='[{"q":"2+2?","options":["3","4"],"answer":1}]'></textarea></div><div class="field full"><label class="check"><input id="fPublish" type="checkbox" checked> Publish immediately</label></div><div class="field full"><button class="btn pink" type="submit">＋ Add Lecture</button></div></form></div><div class="panel"><h3 style="font:650 18px Poppins;margin-top:0">Lecture number helper</h3><div class="notice">Select a chapter and the system can suggest the next number. You can still override it manually.</div><div id="adminPreview" style="margin-top:14px"></div></div></div>`}
  window.refreshAdminSubjects=()=>refreshAdminChapters();window.refreshAdminChapters=()=>{const cls=document.getElementById('fClass')?.value,sub=document.getElementById('fSubject')?.value,sel=document.getElementById('fChapter');if(!sel)return;const cs=state.db[cls][sub].chapters;sel.innerHTML=cs.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('');suggestNo();};function suggestNo(){const cls=document.getElementById('fClass')?.value,sub=document.getElementById('fSubject')?.value,cid=document.getElementById('fChapter')?.value;const c=chapterBy(cls,sub,cid);if(!c)return;const n=Math.max(0,...c.lectures.map(l=>Number(l.no)||0))+1;document.getElementById('fNo').value=n;document.getElementById('adminPreview').innerHTML=`<div class="panel" style="padding:13px;background:#070c13"><b>Next suggested:</b> Lecture ${n}<br><span class="muted">Existing: ${c.lectures.length?c.lectures.map(l=>l.no).sort((a,b)=>a-b).join(', '):'none'}</span></div>`}
  function addLecture(e){e.preventDefault();const cls=fClass.value,sub=fSubject.value,c=chapterBy(cls,sub,fChapter.value);if(!c)return;let quiz=[];try{quiz=fQuiz.value?JSON.parse(fQuiz.value):[]}catch(err){toast('Quiz JSON invalid');return}const l={id:crypto.randomUUID?.()||('lec-'+Date.now()),no:Number(fNo.value)||c.lectures.length+1,title:fTitle.value.trim(),teacher:fTeacher.value.trim(),videoUrl:fVideo.value.trim(),thumbnail:fThumb.value.trim(),notesUrl:fNotes.value.trim(),dppUrl:fDpp.value.trim()||null,moduleUrl:fModule.value.trim(),pyqUrl:fPyq.value.trim(),solutionsUrl:fSolutions.value.trim(),quiz,published:fPublish.checked,duration:0,createdAt:new Date().toISOString()};c.lectures.push(l);c.lectures.sort((a,b)=>a.no-b.no);saveObj();toast(`Lecture ${l.no} added ✓`);e.target.reset();refreshAdminChapters()}
  function adminChapterForm(){return `<div class="panel"><h3 style="font:650 18px Poppins;margin-top:0">Add chapter</h3><form class="form" onsubmit="addChapter(event)"><div class="field"><label>Class</label><select id="cClass"><option>11th</option><option>12th</option></select></div><div class="field"><label>Subject</label><select id="cSubject"><option>Physics</option><option>Chemistry</option><option>Maths</option></select></div><div class="field"><label>Chapter name</label><input id="cName" required placeholder="Chapter title"></div><div class="field"><label>Order</label><input id="cOrder" type="number" min="1" placeholder="Auto"></div><div class="field full"><button class="btn pink">＋ Add Chapter</button></div></form></div>`}
  window.addChapter=e=>{e.preventDefault();const cls=cClass.value,sub=cSubject.value,name=cName.value.trim();const obj=state.db[cls][sub],order=Number(cOrder.value)||obj.chapters.length+1;obj.chapters.push({id:slug(name),name,order,lectures:[]});obj.chapters.sort((a,b)=>a.order-b.order);saveObj();toast('Chapter added ✓');e.target.reset()};
  function manageAdmin(){const ls=allLectures();return `<div class="panel"><div class="section-head"><div><h2>Manage content</h2><p>Edit/delete/hide individual lectures.</p></div></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Class</th><th>Subject</th><th>Chapter</th><th>No.</th><th>Title</th><th>Published</th><th>Actions</th></tr></thead><tbody>${ls.map(l=>`<tr><td>${l.cls}</td><td>${l.sub}</td><td>${esc(l.chapter)}</td><td>${l.no}</td><td>${esc(l.title)}</td><td>${l.published?'Yes':'Hidden'}</td><td><div class="table-actions"><button class="btn" onclick="editLecture('${l.cls}','${l.sub}','${l.chapterId}','${l.id}')">Edit</button><button class="btn danger" onclick="deleteLecture('${l.cls}','${l.sub}','${l.chapterId}','${l.id}')">Delete</button></div></td></tr>`).join('')||'<tr><td colspan="7">No lectures.</td></tr>'}</tbody></table></div></div>`}
  function editLecture(cls,sub,cid,lid){const c=chapterBy(cls,sub,cid),l=c.lectures.find(x=>x.id===lid);openModal(`<div class="modal-box"><div class="modal-head"><h3>Edit Lecture ${l.no}</h3><button class="btn icon-btn" onclick="closeModal()">✕</button></div><form class="form" onsubmit="saveLectureEdit(event,'${cls}','${sub}','${cid}','${lid}')"><div class="field"><label>Number</label><input name="no" type="number" value="${l.no}"></div><div class="field"><label>Title</label><input name="title" value="${esc(l.title)}"></div><div class="field"><label>Teacher</label><input name="teacher" value="${esc(l.teacher)}"></div><div class="field"><label>Video URL</label><input name="videoUrl" value="${esc(l.videoUrl)}"></div><div class="field"><label>Thumbnail URL</label><input name="thumbnail" value="${esc(l.thumbnail)}"></div><div class="field"><label>Notes</label><input name="notesUrl" value="${esc(l.notesUrl)}"></div><div class="field"><label>DPP</label><input name="dppUrl" value="${esc(l.dppUrl||'')}"></div><div class="field"><label>Module</label><input name="moduleUrl" value="${esc(l.moduleUrl)}"></div><div class="field"><label>PYQ</label><input name="pyqUrl" value="${esc(l.pyqUrl)}"></div><div class="field"><label>Solutions</label><input name="solutionsUrl" value="${esc(l.solutionsUrl)}"></div><div class="field"><label class="check"><input name="published" type="checkbox" ${l.published?'checked':''}> Published</label></div><div class="field full"><button class="btn pink">Save changes</button></div></form></div>`)}
  window.editLecture=editLecture;window.saveLectureEdit=(e,cls,sub,cid,lid)=>{e.preventDefault();const c=chapterBy(cls,sub,cid),l=c.lectures.find(x=>x.id===lid),f=new FormData(e.target);for(const k of ['no','title','teacher','videoUrl','thumbnail','notesUrl','dppUrl','moduleUrl','pyqUrl','solutionsUrl'])l[k]=f.get(k);l.no=Number(l.no)||1;l.published=f.has('published');saveObj();closeModal();toast('Lecture updated ✓');render()};window.deleteLecture=(cls,sub,cid,lid)=>{if(!confirm('Delete this lecture?'))return;const c=chapterBy(cls,sub,cid);c.lectures=c.lectures.filter(x=>x.id!==lid);delete state.progress[lid];saveObj();toast('Lecture deleted');render()};
  function backupAdmin(){return `<div class="panel"><h3 style="font:650 18px Poppins;margin-top:0">Backup & restore</h3><p class="muted" style="font-size:12px">Export your local content/progress before clearing browser data. Importing replaces the current local state.</p><div class="toolbar"><button class="btn blue" onclick="exportData()">Export JSON</button><label class="btn">Import JSON <input id="importFile" type="file" accept="application/json" hidden onchange="importData(event)"></label><button class="btn danger" onclick="resetAll()">Reset everything</button></div><div class="notice">For real cross-device admin, secure login and cloud storage, connect Supabase/Firebase later. Never put a private API/service key in frontend code.</div></div>`}
  window.exportData=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));a.download='ghazi-jee-2028-backup.json';a.click();URL.revokeObjectURL(a.href)};window.importData=e=>{const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const x=normalize(JSON.parse(r.result));localStorage.setItem(KEY,JSON.stringify(x));location.reload()}catch(err){toast('Invalid backup')}};r.readAsText(f)};window.resetAll=()=>{if(confirm('Delete all local data and restore default syllabus?')){localStorage.removeItem(KEY);location.reload()}};
  window.adminTab=tab=>{const body=document.getElementById('adminBody');if(!body)return;if(tab==='lecture')body.innerHTML=adminLectureForm();if(tab==='chapter')body.innerHTML=adminChapterForm();if(tab==='manage')body.innerHTML=manageAdmin();if(tab==='data')body.innerHTML=backupAdmin();if(tab==='lecture')refreshAdminChapters()};

  function openModal(html){document.getElementById('modal-root').innerHTML=`<div class="modal show" onclick="if(event.target===this)closeModal()">${html}</div>`}function closeModal(){const v=document.getElementById('lectureVideo');if(v?._cleanup)v._cleanup();document.getElementById('modal-root').innerHTML=''}window.closeModal=closeModal;
  function render(){const r=route();if(r[0]==='home')app.innerHTML=home();else if(r[0]==='dashboard')app.innerHTML=home();else if(r[0]==='class')app.innerHTML=classPage(r[1]);else if(r[0]==='subject')app.innerHTML=subjectPage(r[1],r[2]);else if(r[0]==='chapter')app.innerHTML=chapterPage(r[1],r[2],r[3]);else if(r[0]==='search')app.innerHTML=searchPage();else if(r[0]==='analytics')app.innerHTML=analyticsPage();else if(r[0]==='planner')app.innerHTML=plannerPage();else if(r[0]==='admin')app.innerHTML=adminPage();updateTimerUI();if(route()[0]==='admin'&&sessionStorage.getItem('ghazi_admin')==='yes')refreshAdminChapters()}
  render();
})();
